services:
  - type: web
    name: qmechanicsai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run sapp.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    envVars:
      - key: HF_TOKEN
        value: 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
